Game log: fix a crash on join + 4 broken module loot tables
Gracz: "zobacz logi". Log pokazal dwa realne bledy (oba naprawione):

1) KRYTYCZNY - gracz nie mogl zostac w swiecie:
   EncoderException: Failed to encode packet 'clientbound/minecraft:update_recipes'
   Caused by: IllegalStateException: Can't encode 'VeloceCaseDisassemblyRecipe@7c79f27',
               expected 'VeloceCaseDisassemblyRecipe@707f616'
   Przyczyna: StreamCodec.unit(...) koduje WYLACZNIE instancje przekazana
   w konstruktorze, a receptura wczytana z datapacku jest inna instancja.
   FIX: StreamCodec.of(encoder, decoder) - nic nie zapisujemy (receptura nie ma
   pol), a przy odczycie tworzymy nowa instancje. Komentarz w kodzie ostrzega
   przed powrotem do "unit".

2) 4 loot table modulow Mekanism wskazywaly NIEISTNIEJACE itemy
   ("Unknown registry key in ResourceKey[minecraft:item]:
   craftingveloce:veloce_crusher_module" - bez prefiksu moda), wiec te bloki
   nie dropily NIC.
   Przyczyna: generator loot table dokladal brakujace pliki, ale ISTNIEJACE
   zostawial nietkniete - stare, bledne wpisy przezyly zmiane nazw blokow.
   FIX: generator porownuje teraz tresc z oczekiwana i NAPRAWIA rozjazd
   (4 pliki przepisane), a nowy guard validate_loot_item_ids pilnuje, ze kazda
   loot table wskazuje istniejacy item (kalibracja: podmiana na nieistniejace id
   jest lapana).

Z loga (bez zmian, zachowanie poprawne): "3 node(s) of the network could not be
read (chunk not loaded)" to komunikat projektowy o wezlach w niewczytanych
chunkach, a "Flywheel backend fell back ..." to log Flywheel, nie nasz.